# Generated by Django 3.0.13 on 2021-04-01 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210401_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='course',
            new_name='Course',
        ),
    ]
