# Generated by Django 3.0.13 on 2021-04-12 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210401_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.RemoveField(
            model_name='content',
            name='order',
        ),
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
    ]
